---
# Adapted from @pvandyken's composite action
name: Build and cache Python project
description: Install project dependencies and optionally install project
inputs:
  python-version:
    description: Python version to setup
    required: true
  cache-id:
    description: Reference id to define cache
    required: false
    default: ${{ github.event.pull_request.id || github.event.after }}
  manager:
    description: Dependency manager used (e.g. poetry)
    required: false
    default: "poetry"
  install-library:
    description: Boolean string to indicate if project library should be installed
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v3

    # Setup & configure dependency manager
    - name: Cache manager installation
      uses: actions/cache@v3
      id: cached-manager
      with:
        path: ~/.local
        key: ${{ runner.os }}-${{ inputs.manager }}-${{ inputs.cache-id }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      if: inputs.manager == 'poetry' && steps.cached-manager.outputs.cache-hit != 'true'
      with:
        virtualenvs-create: true

    # Setup & configure Python
    - name: Setup python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
        cache: "${{ inputs.manager }}"

    # Install dependencies with manager, if necessary
    - name: Install dependencies
      if: inputs.manager == 'poetry' && steps.setup-python.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-interaction --no-ansi --no-root --with dev --all-extras

    - name: Install library
      if: inputs.manager == 'poetry' && inputs.install-library
      shell: bash
      run: poetry install --no-interaction --no-ansi --all-extras
