version: 2
updates:
  # Workflow
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. 
    # (You don't need to specify `/.github/workflows` for `directory`. 
    # You can use `directory: "/"`.)
    directory: "/"
    # Run on first of each month
    schedule:
      interval: "monthly"
    # Group to submit a single PR if possible
    groups:
      github-actions:
        patterns:
          - "*"

  # Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/action-general_task-commitProtected"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/action-setup_task-installPyProject"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/action-version_task-commit"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/action-version_task-updatePrereleaseVersion"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/action-version_task-updateReleaseVersion"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"