---
# Assumes:
#   - release-drafter is used to create release notes
#     (see https://github.com/marketplace/actions/release-drafter)
#   - main branch is protected
name: Release package on GH
on:
  workflow_call:
    inputs:
      comments:
        description: Comments
        required: false
        type: string
      project-metadata:
        description: File containing project metadata (e.g. pyproject.toml)
        required: false
        default: pyproject.toml
        type: string
    secrets:
      BP-PAT:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Print author
        run: |
          echo "Author: ${{ github.triggering_actor }}"
          echo "Comments: ${{ inputs.comments }}"

      - name: Grab release version
        id: semver
        uses: ./.github/actions/action-version_task-updateReleaseVersion
        with:
          project-metadata: ${{ inputs.project-metadata }}
          bp-pat: ${{ secrets.BP-PAT }}

      - name: Update version in ${{ inputs.project-metadata }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: ${{ inputs.project-metadata }}
          find: version = "(?:([0-9]+\.[0-9]+\.[0-9]+.+)|([0-9]+\.[0-9]+\.[0-9]+))"
          replace: version = "${{ steps.semver.outputs.new-version }}"

      - name: Commit changes and publish changelog
        uses: ./.github/actions/action-version_task-commit
        with:
          version: ${{ steps.semver.outputs.new-version }}
          bp-pat: ${{ secrets.BP-PAT }}
          release: True
          branch: ${{ steps.semver.outputs.branch }}
