---
# Assumes:
#   - release-drafter is used to create release notes
#     (see https://github.com/marketplace/actions/release-drafter)
#   - main branch is protected
name: Bump version
on:
  workflow_call:
    inputs:
      project-metadata:
        description: File containing project metadata (e.g. pyproject.toml)
        required: false
        default: pyproject.toml
        type: string
    secrets:
      BP-PAT:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Grab previous version
        id: semver
        uses: ./.github/actions/action-version_task-updatePrereleaseVersion
        with:
          project-metadata: ${{ inputs.project-metadata }}
          bp-pat: ${{ secrets.BP-PAT }}

      - name: Update version in ${{ inputs.project-metadata }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: ${{ inputs.project-metadata }}
          find: version = "(?:([0-9]+\.[0-9]+\.[0-9]+.+)|([0-9]+\.[0-9]+\.[0-9]+))"
          replace: version = "${{ steps.semver.outputs.new-version }}"

      - name: Commit changes
        uses: ./.github/actions/action-version_task-commit
        with:
          version: ${{ steps.semver.outputs.new-version }}
          bp-pat: ${{ secrets.BP-PAT }}
